# vim: set expandtab ts=2:
name: West of the Sun
author: Méliusz Luca
email: luca@westofthesun.hu
markdown: kramdown
lang: hu
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
gems:
  - jekyll-sitemap
